//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meellyy.TestingConsoleClient.RetrieveData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="RetrieveData.IRetrieveData")]
    public interface IRetrieveData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IRetrieveData/retrieveFromTestTable", ReplyAction="http://Microsoft.ServiceModel.Samples/IRetrieveData/retrieveFromTestTableResponse" +
            "")]
        string retrieveFromTestTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IRetrieveData/retrieveFromTestTable", ReplyAction="http://Microsoft.ServiceModel.Samples/IRetrieveData/retrieveFromTestTableResponse" +
            "")]
        System.Threading.Tasks.Task<string> retrieveFromTestTableAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRetrieveDataChannel : Meellyy.TestingConsoleClient.RetrieveData.IRetrieveData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveDataClient : System.ServiceModel.ClientBase<Meellyy.TestingConsoleClient.RetrieveData.IRetrieveData>, Meellyy.TestingConsoleClient.RetrieveData.IRetrieveData {
        
        public RetrieveDataClient() {
        }
        
        public RetrieveDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetrieveDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetrieveDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetrieveDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string retrieveFromTestTable() {
            return base.Channel.retrieveFromTestTable();
        }
        
        public System.Threading.Tasks.Task<string> retrieveFromTestTableAsync() {
            return base.Channel.retrieveFromTestTableAsync();
        }
    }
}
